//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName = "ISecurityService")]
public interface ISecurityService
{

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ISecurityService/GetUserFeatures", ReplyAction = "http://tempuri.org/ISecurityService/GetUserFeaturesResponse")]
    string[] GetUserFeatures(int stanlibID);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface ISecurityServiceChannel : ISecurityService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class SecurityServiceClient : System.ServiceModel.ClientBase<ISecurityService>, ISecurityService
{

    public SecurityServiceClient()
    {
    }

    public SecurityServiceClient(string endpointConfigurationName) :
        base(endpointConfigurationName)
    {
    }

    public SecurityServiceClient(string endpointConfigurationName, string remoteAddress) :
        base(endpointConfigurationName, remoteAddress)
    {
    }

    public SecurityServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
        base(endpointConfigurationName, remoteAddress)
    {
    }

    public SecurityServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
        base(binding, remoteAddress)
    {
    }

    public string[] GetUserFeatures(int stanlibID)
    {
        return base.Channel.GetUserFeatures(stanlibID);
    }
}
