//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 4.0.50826.0
// 
namespace BrokerTools.Data.SecurityProxy {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SecurityProxy.ISecurityService")]
    public interface ISecurityService {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ISecurityService/GetUserFeatures", ReplyAction="http://tempuri.org/ISecurityService/GetUserFeaturesResponse")]
        System.IAsyncResult BeginGetUserFeatures(int stanlibID, System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<string> EndGetUserFeatures(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISecurityServiceChannel : BrokerTools.Data.SecurityProxy.ISecurityService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetUserFeaturesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetUserFeaturesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<string> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<string>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SecurityServiceClient : System.ServiceModel.ClientBase<BrokerTools.Data.SecurityProxy.ISecurityService>, BrokerTools.Data.SecurityProxy.ISecurityService {
        
        private BeginOperationDelegate onBeginGetUserFeaturesDelegate;
        
        private EndOperationDelegate onEndGetUserFeaturesDelegate;
        
        private System.Threading.SendOrPostCallback onGetUserFeaturesCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public SecurityServiceClient() {
        }
        
        public SecurityServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SecurityServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SecurityServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SecurityServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<GetUserFeaturesCompletedEventArgs> GetUserFeaturesCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult BrokerTools.Data.SecurityProxy.ISecurityService.BeginGetUserFeatures(int stanlibID, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetUserFeatures(stanlibID, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<string> BrokerTools.Data.SecurityProxy.ISecurityService.EndGetUserFeatures(System.IAsyncResult result) {
            return base.Channel.EndGetUserFeatures(result);
        }
        
        private System.IAsyncResult OnBeginGetUserFeatures(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int stanlibID = ((int)(inValues[0]));
            return ((BrokerTools.Data.SecurityProxy.ISecurityService)(this)).BeginGetUserFeatures(stanlibID, callback, asyncState);
        }
        
        private object[] OnEndGetUserFeatures(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<string> retVal = ((BrokerTools.Data.SecurityProxy.ISecurityService)(this)).EndGetUserFeatures(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetUserFeaturesCompleted(object state) {
            if ((this.GetUserFeaturesCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetUserFeaturesCompleted(this, new GetUserFeaturesCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetUserFeaturesAsync(int stanlibID) {
            this.GetUserFeaturesAsync(stanlibID, null);
        }
        
        public void GetUserFeaturesAsync(int stanlibID, object userState) {
            if ((this.onBeginGetUserFeaturesDelegate == null)) {
                this.onBeginGetUserFeaturesDelegate = new BeginOperationDelegate(this.OnBeginGetUserFeatures);
            }
            if ((this.onEndGetUserFeaturesDelegate == null)) {
                this.onEndGetUserFeaturesDelegate = new EndOperationDelegate(this.OnEndGetUserFeatures);
            }
            if ((this.onGetUserFeaturesCompletedDelegate == null)) {
                this.onGetUserFeaturesCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetUserFeaturesCompleted);
            }
            base.InvokeAsync(this.onBeginGetUserFeaturesDelegate, new object[] {
                        stanlibID}, this.onEndGetUserFeaturesDelegate, this.onGetUserFeaturesCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override BrokerTools.Data.SecurityProxy.ISecurityService CreateChannel() {
            return new SecurityServiceClientChannel(this);
        }
        
        private class SecurityServiceClientChannel : ChannelBase<BrokerTools.Data.SecurityProxy.ISecurityService>, BrokerTools.Data.SecurityProxy.ISecurityService {
            
            public SecurityServiceClientChannel(System.ServiceModel.ClientBase<BrokerTools.Data.SecurityProxy.ISecurityService> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginGetUserFeatures(int stanlibID, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = stanlibID;
                System.IAsyncResult _result = base.BeginInvoke("GetUserFeatures", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<string> EndGetUserFeatures(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<string> _result = ((System.Collections.ObjectModel.ObservableCollection<string>)(base.EndInvoke("GetUserFeatures", _args, result)));
                return _result;
            }
        }
    }
}
